### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by TheOdd** [TheOdd/disp-dist-calc#1]
- [x] Add support for floats. Right now, only numbers without decimal points can be inputted.
- [ ] Convert all component view management to `react-columns` for more dynamic and mobile-friendly app.
- [ ] Find a way to color individual strokes and dynamically render them. Or switch to `<Line />` shape from Konva and do stroke colors for each, ultimately refactoring entire draw method.
